package motassemja.github.com.moauth.exceptions;

/**
 * Created by moja on 12.06.2017.
 */

public enum MoAuthExceptionReason {
    REASON_UNKNOWN,
    REASON_INTERNAL_ERROR,
    REASON_NETWORK_ERROR,
    REASON_RESPONSE_NOT_OK,
    REASON_INVALID_REQUEST,
    REASON_BAD_RESPONSE,
    REASON_RESOURCE_NOT_FOUND,
    REASON_INVALID_CALLBACK,
    REASON_NO_CONTENT,
    REASON_NOT_AUTHORIZED,
    REASON_NOT_AUTHENTICATED,
    REASON_BACKEND_ERROR,
    REASON_CONFIGURATION_ERROR,
    REASON_PERMISSIONS_NOT_LOADED,
    REASON_CANCELED,
    REASON_UNSUPPORTED_RESPONSE_TYPE,
    REASON_UNAUTHORIZED_CLIENT,
    REASON_ACCESS_DENIED,
    REASON_INVALID_SCOPE,
    REASON_SERVER_ERROR,
    REASON_INVALID_CLIENT,
    REASON_INVALID_GRANT,
    REASON_UNSUPPORTED_GRANT_TYPE,
    REASON_INVALID_REDIRECT_URI
}
